spring.application.name=group_5

#SQL SERVER
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ChefBookingDB;encrypt=false;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=Abc@12345
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# JWT Configuration
jwt.secret=5Z4qX9vL2k8nP7mJ3rT6yB1cD0eF9gH8iJ5kL2mN4oP6qR8sT0uV
jwt.expiration=900000