spring.application.name=group_5

#SQL SERVER
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ChefBookingDB;encrypt=false;trustServerCertificate=true;
spring.datasource.username=long
spring.datasource.password=1
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ============ C?U HÌNH SPRING DATA JPA (Hibernate) ============
# 'update': T? ??ng c?p nh?t (thêm c?t, t?o b?ng) khi Entity thay ??i. R?t t?t cho dev.
spring.jpa.hibernate.ddl-auto=update

# 'true': Hi?n th? các câu l?nh SQL mà Spring Boot ch?y trong console (?? debug)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect